# Generated by Django 5.2.12 on 2026-05-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='projects/')),
                ('tech_stack', models.CharField(help_text='Ex: Django, React, PostgreSQL', max_length=255)),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub')),
                ('live_url', models.URLField(blank=True, verbose_name='Demo en ligne')),
                ('featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
