# Generated by Django 5.2.12 on 2026-05-03 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField(verbose_name='Contenu')),
                ('excerpt', models.TextField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='blog/')),
                ('tags', models.CharField(blank=True, help_text='Separes par virgules', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publie')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
